### ISSUE TITLE
Jump to Oldest Unread

### ISSUE THREAD

**Issue by georgedorn** [enkiv2/fern#5]
Getting to Timeline Zero makes a lot more sense if you start at the oldest unread toot, rather than reading everything backwards.

Reverse chronological is for firehoses you don't intend to drink everything from.

**Comment by enkiv2** [comment]
This is a good point. I'll implement a key for jumping to oldest unread (probably 'O').

The sensible way to do this is to reuse some of the code currently used for searching.

**Comment by enkiv2** [comment]
OK, this is implemented in 67e416361307a6c775f4be2228749c4dece93699

To make this more useful, I will need to change the behavior of N/P/n/p so that going back pages is more reliable (so I'm keeping this issue open for the time being).

**Comment by enkiv2** [comment]
OK, I've changed behavior of page offsets in 02505419488188c3ccb4c0ea76ccefb825a456c0 and changed the behavior of fill-in in 6a86d3ea8aba768b928b8ea0d86c95dd486bfc67, so in its current state, jumping to the end and hitting p / P should be a reasonable way to get to timeline zero.

Please note that, because of my changes here, n and p will skip over pages wherein every message has been read (without warning).
